bulk_site_creation/urls.py
from django.conf.urls import url

from bulk_site_creation import views, api


urlpatterns = [
    url(r'^lti_auth_error$', views.lti_auth_error, name='lti_auth_error'),
    url(r'^tool_config$', views.tool_config, name='tool_config'),
    url(r'^lti_launch$', views.lti_launch, name='lti_launch'),
    url(r'^index$', views.index, name='index'),
    url(r'^audit', views.audit, name='audit'),
    url(r'^course_selection$', views.course_selection, name='course_selection'),
    url(r'^create_job$', views.create_job, name='create_job'),
    url(r'^bulk_job_detail/(?P<bulk_job_id>[\d]+)$', views.bulk_job_detail, name='bulk_job_detail'),
    url(r'^api/schools$', api.schools, name='api_schools'),
    url(r'^api/schools/(?P<sis_account_id>[:\w]+)/terms$', api.terms, name='api_terms'),
    url(r'^api/schools/(?P<sis_account_id>[:\w]+)/departments$', api.departments, name='api_departments'),
    url(r'^api/schools/(?P<sis_account_id>[:\w]+)/course_groups$', api.course_groups, name='api_course_groups'),
    url(r'^api/terms/(?P<sis_term_id>[:\w]+)/accounts/(?P<sis_account_id>[:\w]+)/course_instances$', api.course_instances, name='api_course_instances'),
    url(r'^api/terms/(?P<sis_term_id>[:\w]+)/accounts/(?P<sis_account_id>[:\w]+)/course_instance_summary$', api.course_instance_summary, name='api_course_instance_summary'),
    url(r'^api/bulk_jobs/(?P<bulk_job_id>[\d]+)/course_jobs$', api.course_jobs, name='api_course_jobs'),
]

canvas_course_creation/urls.py
from django.conf.urls import include, url
from canvas_course_site_wizard import urls as ccsw_urls

urlpatterns = [
    #url(r'^admin/', include(admin.site.urls)),
    url(r'^not_authorized/', 'icommons_ui.views.not_authorized', name="not_authorized"),
    url(r'^pin/', include('icommons_common.auth.urls', namespace="pin")),
    url(r'^bulk_site_creation/', include('bulk_site_creation.urls', namespace='bulk_site_creation')),
    url(r'^canvas-course-site-wizard/', include(ccsw_urls)),
]

handler403 = 'canvas_course_creation.views.handler403'
handler404 = 'canvas_course_creation.views.handler404'
handler500 = 'canvas_course_creation.views.handler500'

bulk_site_creation/models.py
from django.conf import settings

from icommons_common.models import CourseInstance

from canvas_course_site_wizard.models import CanvasCourseGenerationJob


def get_course_instance_query_set(sis_term_id, sis_account_id):
    filters = {'exclude_from_isites': 0, 'term_id': sis_term_id}

    (account_type, account_id) = sis_account_id.split(':')
    if account_type == 'school':
        filters['course__school'] = account_id
    elif account_type == 'dept':
        filters['course__departments'] = account_id
    elif account_type == 'coursegroup':
        filters['course__course_groups'] = account_id

    return CourseInstance.objects.filter(**filters)


def get_course_instance_summary_data(query_set):
    total_count = query_set.count()

    query_set_without_canvas_site = query_set.filter(canvas_course_id__isnull=True)
    total_without_canvas_site_count = query_set_without_canvas_site.count()
    total_without_canvas_site_with_isites_count = query_set_without_canvas_site.filter(
        sitemap__course_site__site_type_id='isite'
    ).count()
    total_without_canvas_site_with_external_count = query_set_without_canvas_site.filter(
        sitemap__course_site__site_type_id='external'
    ).exclude(sitemap__course_site__external_id__icontains=settings.CANVAS_URL).count()

    query_set_with_canvas_site = query_set.filter(canvas_course_id__isnull=False)
    total_with_canvas_site_count = query_set_with_canvas_site.count()
    total_with_canvas_site_with_isites_count = query_set_with_canvas_site.filter(
        sitemap__course_site__site_type_id='isite'
    ).count()
    total_with_canvas_site_with_external_count = query_set_with_canvas_site.filter(
        sitemap__course_site__site_type_id='external'
    ).exclude(sitemap__course_site__external_id__icontains=settings.CANVAS_URL).count()

    return {
        'recordsTotal': total_count,
        'recordsFiltered': total_count,
        'recordsTotalWithoutCanvasSite': total_without_canvas_site_count,
        'recordsTotalWithoutCanvasSiteWithISite': total_without_canvas_site_with_isites_count,
        'recordsTotalWithoutCanvasSiteWithExternal': total_without_canvas_site_with_external_count,
        'recordsTotalWithCanvasSite': total_with_canvas_site_count,
        'recordsTotalWithCanvasSiteWithISite': total_with_canvas_site_with_isites_count,
        'recordsTotalWithCanvasSiteWithExternal': total_with_canvas_site_with_external_count,
    }


def get_course_job_summary_data(bulk_job_id):
    data = {}
    total_count = CanvasCourseGenerationJob.objects.filter(bulk_job_id=bulk_job_id).count()
    data['recordsTotal'] = total_count
    data['recordsFiltered'] = total_count
    data['recordsComplete'] = CanvasCourseGenerationJob.objects.filter_complete(bulk_job_id=bulk_job_id).count()
    data['recordsSuccessful'] = CanvasCourseGenerationJob.objects.filter_successful(bulk_job_id=bulk_job_id).count()
    data['recordsFailed'] = CanvasCourseGenerationJob.objects.filter_failed(bulk_job_id=bulk_job_id).count()
    return data

bulk_site_creation/views.py
import logging
import json

from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.conf import settings
from django.core.exceptions import PermissionDenied
from django.utils import timezone

from ims_lti_py.tool_config import ToolConfig

from icommons_common.models import School, Term, Department, CourseGroup, Person
from icommons_common.canvas_api.helpers import accounts as canvas_api_accounts
from icommons_common.auth.lti_decorators import has_account_permission

from canvas_course_site_wizard.models import BulkCanvasCourseCreationJob, CanvasCourseGenerationJob

from .models import (
    get_course_instance_query_set,
    get_course_instance_summary_data,
    get_course_job_summary_data
)
from .utils import (
    get_school_data_for_user,
    get_term_data_for_school,
    get_department_data_for_school,
    get_course_group_data_for_school,
    get_term_data,
    get_canvas_site_templates_for_school,
    get_canvas_site_template
)


logger = logging.getLogger(__name__)

COURSE_INSTANCE_FILTERS = ['school', 'term', 'department', 'course_group']


def lti_auth_error(request):
    raise PermissionDenied


@require_http_methods(['GET'])
def tool_config(request):
    env = settings.ENV_NAME if hasattr(settings, 'ENV_NAME') else ''
    url = "%s://%s%s" % (
        request.scheme,
        request.get_host(),
        reverse('bulk_site_creation:lti_launch', exclude_resource_link_id=True)
    )
    lti_tool_config = ToolConfig(
        title="Canvas Site Creator %s" % env,
        launch_url=url,
        secure_launch_url=url,
        description="This LTI tool provides canvas site creation functionality."
    )

    # this is how to tell Canvas that this tool provides an account navigation link:
    lti_tool_config.set_ext_param('canvas.instructure.com', 'account_navigation', {
        'enabled': 'true',
        'text': "Canvas Site Creator %s" % env
    })
    lti_tool_config.set_ext_param('canvas.instructure.com', 'privacy_level', 'public')

    return HttpResponse(lti_tool_config.to_xml(), content_type='text/xml', status=200)


@login_required
@require_http_methods(['POST'])
@csrf_exempt
def lti_launch(request):
    logger.debug("bulk_site_creation launched with params: %s", json.dumps(request.POST.dict(), indent=4))
    return redirect('bulk_site_creation:index')


@login_required
@has_account_permission(canvas_api_accounts.ACCOUNT_PERMISSION_MANAGE_COURSES)
@require_http_methods(['GET'])
def index(request):
    canvas_user_id = request.LTI['custom_canvas_user_id']
    sis_account_id = request.LTI['custom_canvas_account_sis_id']
    ci_filters = {key: request.GET.get(key, '') for key in COURSE_INSTANCE_FILTERS}
    (account_type, _) = canvas_api_accounts.parse_canvas_account_id(sis_account_id)
    schools = []
    terms = []
    departments = []
    course_groups = []
    school = None

    if account_type in canvas_api_accounts.ACCOUNT_TYPES:
        # We are in the context of a SIS type account, so limit options to that context
        school_id = sis_account_id
        if account_type == canvas_api_accounts.ACCOUNT_TYPE_DEPARTMENT:
            department = canvas_api_accounts.get_account_by_sis_account_id(canvas_user_id, sis_account_id)
            department_id = department['sis_account_id']
            school_id = department['parent_account_id']
            ci_filters[canvas_api_accounts.ACCOUNT_TYPE_COURSE_GROUP] = department_id
            departments.append(get_department_data_for_school(canvas_user_id, school_id, department_id))
        elif account_type == canvas_api_accounts.ACCOUNT_TYPE_COURSE_GROUP:
            course_group = canvas_api_accounts.get_account_by_sis_account_id(canvas_user_id, sis_account_id)
            course_group_id = course_group['sis_account_id']
            school_id = course_group['parent_account_id']
            ci_filters[canvas_api_accounts.ACCOUNT_TYPE_COURSE_GROUP] = course_group_id
            course_groups.append(get_course_group_data_for_school(canvas_user_id, school_id, course_group_id))
        school = get_school_data_for_user(canvas_user_id, school_id)
        ci_filters[canvas_api_accounts.ACCOUNT_TYPE_SCHOOL] = school['id']
        schools.append(school)
    else:
        # We are outside the context of a SIS type account, so show all schools
        # that the user has permission to create courses for
        schools = get_school_data_for_user(canvas_user_id)
        school_sis_account_id = ci_filters.get('school')
        if school_sis_account_id:
            school = get_school_data_for_user(canvas_user_id, school_sis_account_id)

    if len(schools) == 0:
        return redirect('not_authorized')

    if school:
        # Populate term, department, and course_group filter options if we already have a school
        school_sis_account_id = school['id']
        terms = get_term_data_for_school(school_sis_account_id)
        if not departments and not course_groups:
            departments = get_department_data_for_school(canvas_user_id, school_sis_account_id)
            course_groups = get_course_group_data_for_school(canvas_user_id, school_sis_account_id)

    return render(request, 'bulk_site_creation/index.html', {
        'filters': ci_filters,
        'schools': schools,
        'terms': terms,
        'departments': departments,
        'course_groups': course_groups
    })


@login_required
@has_account_permission(canvas_api_accounts.ACCOUNT_PERMISSION_MANAGE_COURSES)
@require_http_methods(['GET'])
def audit(request):
    canvas_user_id = request.LTI['custom_canvas_user_id']
    sis_account_id = request.LTI['custom_canvas_account_sis_id']
    (account_type, account_id) = canvas_api_accounts.parse_canvas_account_id(sis_account_id)

    filter_kwargs = {}
    if account_type == canvas_api_accounts.ACCOUNT_TYPE_SCHOOL:
        filter_kwargs['school_id'] = account_id
    elif account_type == canvas_api_accounts.ACCOUNT_TYPE_DEPARTMENT:
        filter_kwargs['sis_department_id'] = account_id
    elif account_type == canvas_api_accounts.ACCOUNT_TYPE_COURSE_GROUP:
        filter_kwargs['sis_course_group_id'] = account_id

    query_set = BulkCanvasCourseCreationJob.objects.filter(**filter_kwargs).order_by('-created_at')

    jobs = []
    creator_ids = set()
    school_ids = set()
    term_ids = set()
    department_ids = set()
    course_group_ids = set()
    for bulk_job in query_set:
        jobs.append(bulk_job)
        creator_ids.add(bulk_job.created_by_user_id)
        school_ids.add(bulk_job.school_id)
        term_ids.add(bulk_job.sis_term_id)
        if bulk_job.sis_department_id:
            department_ids.add(bulk_job.sis_department_id)
        if bulk_job.sis_course_group_id:
            course_group_ids.add(bulk_job.sis_course_group_id)

    creators = {p.univ_id: p for p in Person.objects.filter(univ_id__in=creator_ids)}
    schools = School.objects.in_bulk(school_ids)
    terms = Term.objects.in_bulk(term_ids)
    departments = {}
    if department_ids:
        departments = {
            id: name for id, name in Department.objects.filter(
                department_id__in=department_ids
            ).values_list('department_id', 'name')
        }
    course_groups = {}
    if course_group_ids:
        course_groups = {
            id: name for id, name in CourseGroup.objects.filter(
                course_group_id__in=course_group_ids
            ).values_list('course_group_id', 'name')
        }

    bulk_job_data = []
    for bulk_job in jobs:
        try:
            creator = creators[bulk_job.created_by_user_id]
            creator_name = "%s, %s" % (creator.name_last, creator.name_first)
        except KeyError:
            # Bulk job creator could not be found
            logger.warning("Failed to find bulk canvas site job creator %s", bulk_job.created_by_user_id)
            creator_name = ''

        school = schools[bulk_job.school_id]
        term = terms[bulk_job.sis_term_id]
        department = ''
        if bulk_job.sis_department_id:
            department = departments[bulk_job.sis_department_id]
        course_group = ''
        if bulk_job.sis_course_group_id:
            course_group = course_groups[bulk_job.sis_course_group_id]
        template_canvas_course = get_canvas_site_template(school.school_id, bulk_job.template_canvas_course_id)

        bulk_job_data.append({
            'id': bulk_job.id,
            'created_at': timezone.localtime(bulk_job.created_at).strftime('%b %d, %Y %H:%M:%S'),
            'status': bulk_job.status_display_name,
            'created_by': creator_name,
            'term': term.display_name,
            'school': school.title_short,
            'subaccount': department if department else course_group,
            'template_canvas_course': template_canvas_course,
            'count_course_jobs': CanvasCourseGenerationJob.objects.filter(bulk_job_id=bulk_job.id).count()
        })

    return render(request, 'bulk_site_creation/audit.html', {
        'bulk_job_data': bulk_job_data
    })


@login_required
@has_account_permission(canvas_api_accounts.ACCOUNT_PERMISSION_MANAGE_COURSES)
@require_http_methods(['GET'])
def course_selection(request):
    canvas_user_id = request.LTI['custom_canvas_user_id']
    ci_filters = {key: request.GET.get(key, '') for key in COURSE_INSTANCE_FILTERS}

    try:
        school = get_school_data_for_user(canvas_user_id, ci_filters['school'])
        term = get_term_data(ci_filters['term'])
    except KeyError:
        redirect('bulk_site_creation:index')

    (account_type, school_id) = canvas_api_accounts.parse_canvas_account_id(school['id'])
    canvas_site_templates = get_canvas_site_templates_for_school(school_id)

    account = school
    department = {}

bulk_site_creation/templates/bulk_site_creation/_bulk_job_table_header.html
<tr>
    <th>Started On</th>
    <th>Status</th>
    <th>Started By</th>
    <th># of Courses</th>
    <th>School</th>
    <th>Academic Term</th>
    <th>Department/Course Group</th>
    <th>Template</th>
</tr>

bulk_site_creation/templates/bulk_site_creation/_course_job_table_header.html
<tr>
    <th>Started On</th>
    <th>Status</th>
    <th>Started By</th>
    <th>SIS Course ID</th>
    <th>Course Code</th>
    <th>Course Title</th>
</tr>

bulk_site_creation/templates/bulk_site_creation/audit.html
{% extends 'bulk_site_creation/base.html' %}

{% load static %}
{% load collections %}
{% load django_helpers %}


{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'datatables-1.10.7/media/css/jquery.dataTables.min.css' %}" media="screen"/>
{% endblock css %}

{% block js %}
    <script src="{% static 'datatables-1.10.7/media/js/jquery.dataTables.js' %}"></script>
    <script>
        window.globals.STATIC_URL = '{% settings_value "STATIC_URL" %}';
    </script>
    <script src="{% static 'bulk_site_creation/js/app.js' %}"></script>
    <script src="{% static 'bulk_site_creation/js/controllers/AuditController.js' %}"></script>
{% endblock js %}

{% block body %}
<body class="lti-tool" role="application" ng-app="app">
    <header>
        <h1><a href="{% url 'bulk_site_creation:index' %}">Canvas Site Creator</a> <i class="fa fa-chevron-right"></i> Audit Log</h1>
    </header>
    <main>
        <table id="bulkJobDT" ng-cloak class="display" cellspacing="0" width="100%" ng-controller="AuditController">
            <thead>
                {% include 'bulk_site_creation/_bulk_job_table_header.html' %}
            </thead>
            <tbody>
                {% for bulk_job in bulk_job_data %}
                <tr>
                    <td>{{ bulk_job.created_at }}</td>
                    <td><a href="{% url 'bulk_site_creation:bulk_job_detail' bulk_job.id %}">{{ bulk_job.status }}</a></td>
                    <td>{{ bulk_job.created_by }}</td>
                    <td>{{ bulk_job.count_course_jobs }}</td>
                    <td>{{ bulk_job.school }}</td>
                    <td>{{ bulk_job.term }}</td>
                    <td>{{ bulk_job.subaccount }}</td>
                    <td>
                        <a href="{{ bulk_job.template_canvas_course.canvas_course_url }}">{{ bulk_job.template_canvas_course.canvas_course_name }}</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                {% include 'bulk_site_creation/_bulk_job_table_header.html' %}
            </tfoot>
        </table>
    </main>
</body>
{% endblock body %}

bulk_site_creation/templates/bulk_site_creation/bulk_job_detail.html
{% extends 'bulk_site_creation/base.html' %}

{% load static %}
{% load django_helpers %}


{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'datatables-1.10.7/media/css/jquery.dataTables.min.css' %}" media="screen"/>
    <link rel="stylesheet" href="{% static 'lti-css/progressbar.css' %}">
{% endblock css %}

{% block js %}
    <script src="{% static 'datatables-1.10.7/media/js/jquery.dataTables.js' %}"></script>
    <script>
        window.globals.STATIC_URL = '{% settings_value "STATIC_URL" %}';
        window.globals.CANVAS_URL = '{% settings_value "CANVAS_URL" %}';
    </script>
    <script src="{% static 'bulk_site_creation/js/app.js' %}"></script>
    <script src="{% static 'bulk_site_creation/js/models/ErrorModel.js' %}"></script>
    <script src="{% static 'bulk_site_creation/js/controllers/ErrorController.js' %}"></script>
    <script src="{% static 'bulk_site_creation/js/models/BulkJobDetailModel.js' %}"></script>
    <script src="{% static 'bulk_site_creation/js/controllers/BulkJobDetailController.js' %}"></script>
{% endblock js %}

{% block body %}
<body class="lti-tool" role="application" ng-app="app" ng-controller="BulkJobDetailController">
    <header>
        <h1>
            <a href="{% url 'bulk_site_creation:index' %}">Canvas Site Creator</a>
            <i class="fa fa-chevron-right"></i>
            <a href="{% url 'bulk_site_creation:audit' %}">Audit Log</a>
            <i class="fa fa-chevron-right"></i>
            {% if not bulk_job_complete %}
                Creating Canvas Sites
            {% else %}
                {{ bulk_job.created_at|date:'M d, Y' }}
            {% endif %}
        </h1>
    </header>
    {% include 'bulk_site_creation/views/ErrorView.html' %}
    <main>
        {% if not bulk_job_complete %}
            <p><strong>Creating {{ course_jobs_total }} Canvas site{{ course_jobs_total|pluralize }} for:</strong></p>
        {% else %}
            <h2>Canvas Site Creation Job Completed</h2>
        {% endif %}
        <p>
            {{ school }} <i class="fa fa-chevron-right"></i>
            {{ term }}
            {% if department %}
            <i class="fa fa-chevron-right"></i> {{ department }}
            {% elif course_group %}
            <i class="fa fa-chevron-right"></i> {{ course_group }}
            {% endif %}
        </p>
        {% if not bulk_job_complete %}
            <form>
                <div class="progress">
                    {% verbatim %}
                    <div class="progress-bar" role="progressbar" aria-valuenow="{{ bulkJobDetailModel.completeCourseJobs }}" aria-valuemin="0" aria-valuemax="100" ng-style="getProgressBarStyle()">
                        <span ng-cloak ng-show="bulkJobDetailModel.completeCourseJobs">
                            {{ bulkJobDetailModel.completeCourseJobs }} out of {{ bulkJobDetailModel.totalCourseJobs }} course site creation jobs completed
                        </span>
                    </div>
                    {% endverbatim %}
                </div>

                {% verbatim %}
                <ul class="lists-inline">
                    <li ng-cloak ng-show="bulkJobDetailModel.successfulCourseJobs">
                        <span class="infoBlock-success">
                            <i class="fa fa-check"></i>
                            {{ bulkJobDetailModel.successfulCourseJobs }} of {{ bulkJobDetailModel.totalCourseJobs }} course
                            <ng-pluralize count="bulkJobDetailModel.totalCourseJobs"
                                          when="{'1': 'site',
                                                 'other': 'sites'}">
                            </ng-pluralize>
                            created
                        </span>
                    </li>
                    <li ng-cloak ng-show="bulkJobDetailModel.failedCourseJobs">
                        <span class="infoBlock-error">
                            <i class="fa fa-exclamation-circle"></i>
                            {{ bulkJobDetailModel.failedCourseJobs }} of {{ bulkJobDetailModel.totalCourseJobs }} course site creation
                            <ng-pluralize count="bulkJobDetailModel.totalCourseJobs"
                                          when="{'1': 'job',
                                                 'other': 'jobs'}">
                            </ng-pluralize>
                            failed
                        </span>
                    </li>
                </ul>
                {% endverbatim %}
            </form>
        {% else %}
            <p>Below is a summary of the Canvas site creation job:</p>
            <ul class="lists-inline">
                {% if course_jobs_successful %}
                <li>
                    <span class="infoBlock-success">
                        <i class="fa fa-check"></i>
                        {{ course_jobs_successful }} of {{ course_jobs_complete }} course site{{ course_jobs_complete|pluralize }} created
                    </span>
                </li>
                {% endif %}
                {% if course_jobs_failed %}
                <li>
                    <span class="infoBlock-error">
                        <i class="fa fa-exclamation-circle"></i>
                        {{ course_jobs_failed }} of {{ course_jobs_complete }} course site creation job{{ course_jobs_failed|pluralize }} failed
                    </span>
                </li>
                {% endif %}
            </ul>
        {% endif %}
        <table id="courseJobDT" ng-cloak data-bulk_job_id="{{ bulk_job.id }}" data-bulk_job_complete="{% if bulk_job_complete %}true{% endif %}" class="display" cellspacing="0" width="100%">
            <thead>
                {% include 'bulk_site_creation/_course_job_table_header.html' %}
            </thead>
            <tfoot>
                {% include 'bulk_site_creation/_course_job_table_header.html' %}
            </tfoot>
        </table>
    </main>
</body>
{% endblock body %}

bulk_site_creation/templates/bulk_site_creation/index.html
{% extends 'bulk_site_creation/base.html' %}

{% load static %}
{% load collections %}
{% load django_helpers %}


{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'datatables-1.10.7/media/css/jquery.dataTables.min.css' %}" media="screen"/>
    <link rel="stylesheet" type="text/css" href="{% static 'datatables-bootstrap3/BS3/assets/css/datatables.css' %}" media="screen"/>
{% endblock css %}

{% block js %}
    <script src="{% static 'datatables-1.10.7/media/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'datatables-bootstrap3/BS3/assets/js/datatables.js' %}"></script>
    <script>
        window.globals.STATIC_URL = '{% settings_value "STATIC_URL" %}';
    </script>
    {% include 'bulk_site_creation/_selected_filters.html' %}
    {% include 'bulk_site_creation/_filter_options.html' %}
    <script src="{% static 'bulk_site_creation/js/app.js' %}"></script>
    <script src="{% static 'bulk_site_creation/js/models/ErrorModel.js' %}"></script>
    <script src="{% static 'bulk_site_creation/js/models/CourseInstanceFilterModel.js' %}"></script>
    <script src="{% static 'bulk_site_creation/js/models/CourseInstanceModel.js' %}"></script>
    <script src="{% static 'bulk_site_creation/js/controllers/IndexController.js' %}"></script>
    <script src="{% static 'bulk_site_creation/js/controllers/ErrorController.js' %}"></script>
    <script src="{% static 'bulk_site_creation/js/controllers/CourseInstanceFilterController.js' %}"></script>
{% endblock js %}

{% block body %}
<body class="lti-tool" role="application" ng-app="app" ng-controller="IndexController">
    <header>
        <h1><a href="{% url 'bulk_site_creation:index' %}">Canvas Site Creator</a></h1>
    </header>
    {% include 'bulk_site_creation/views/ErrorView.html' %}
    <main class="float-left col-60">
        {% include 'bulk_site_creation/views/CourseInstanceFilterView.html' %}
        <div ng-cloak ng-show="showSummaryLoading()">
            <img src="{% static 'images/ajax-loader-large.gif' %}"/>
        </div>
        <div ng-cloak ng-show="showSummary()">
            <h2>
                <ng-pluralize count="courseInstanceModel.totalCourses"
                              when="{'0': 'There are 0 courses in this term:',
                                     '1': 'There is 1 course in this term:',
                                     'other': 'There are {} courses in this term:'}">
                </ng-pluralize>
            </h2>
            <ul>
                <li>
                    <ng-pluralize count="courseInstanceModel.totalCoursesWithCanvasSite"
                              when="{'0': '0 courses with Canvas sites ',
                                     '1': '1 course with a Canvas site ',
                                     'other': '{} courses with Canvas sites '}">
                    </ng-pluralize>
                    (<ng-pluralize count="courseInstanceModel.totalCoursesWithCanvasSiteWithISite"
                              when="{'0': '0 iSites, ',
                                     '1': '1 iSites, ',
                                     'other': '{} iSites, '}">
                    </ng-pluralize>
                    {% verbatim %}
                    {{ courseInstanceModel.totalCoursesWithCanvasSiteWithExternal }} external)
                    {% endverbatim %}
                </li>
                <li>
                    <ng-pluralize count="courseInstanceModel.totalCoursesWithoutCanvasSite"
                              when="{'0': '0 courses without Canvas sites ',
                                     '1': '1 course without a Canvas site ',
                                     'other': '{} courses without Canvas sites '}">
                    </ng-pluralize>
                    (<ng-pluralize count="courseInstanceModel.totalCoursesWithoutCanvasSiteWithISite"
                              when="{'0': '0 iSites, ',
                                     '1': '1 iSites, ',
                                     'other': '{} iSites, '}">
                    </ng-pluralize>
                    {% verbatim %}
                    {{ courseInstanceModel.totalCoursesWithoutCanvasSiteWithExternal }} external)
                    {% endverbatim %}
                    <button type="button" class="btn btn-submit" id="createSitesButton" ng-disabled="createDisabled()" ng-click="handleCreate($event)" data-href="{% url 'bulk_site_creation:course_selection' %}">Create Canvas Sites</button></li>
                </li>
            </ul>
        </div>
        <div class="infoBlock-help users-found">
            <p>Visit the <a href="{% url 'bulk_site_creation:audit' %}">site creator audit log</a> to view previously created Canvas course sites.</p>
        </div>
    </main>
</body>
{% endblock body %}